apiVersion: v1
kind: Service
metadata:
  labels:
    cctodoapp.service: mongodb
  name: mongodb-service
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    cctodoapp.service: mongodb
