version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    command: mongod --auth
    networks:
      - ccnetwork
  ccapp1:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    depends_on:
      - mongodb
    networks:
      - ccnetwork

  ccapp2:
    build: .
    restart: always
    ports:
      - 3001:3000
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    depends_on:
      - mongodb
    networks:
      - ccnetwork

  ccapp3:
    build: .
    restart: always
    ports:
      - 3002:3000
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    depends_on:
      - mongodb
    networks:
      - ccnetwork

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ccapp1
      - ccapp2
      - ccapp3
    networks:
      - ccnetwork

networks:
  ccnetwork:
